// Static imports to avoid webpack issues with dynamic imports
import * as exodus from './exodus';
import * as leviticus from './leviticus';
import * as numbers from './numbers';
import * as deuteronomy from './deuteronomy';
import * as joshua from './joshua';
import * as judges from './judges';
import * as ruth from './ruth';
import * as samuel1 from './1-samuel';
import * as samuel2 from './2-samuel';
import * as kings1 from './1-kings';
import * as kings2 from './2-kings';
import * as chronicles1 from './1-chronicles';
import * as chronicles2 from './2-chronicles';
import * as ezra from './ezra';
import * as nehemiah from './nehemiah';
import * as esther from './esther';
import * as job from './job';
import * as proverbs from './proverbs';
import * as ecclesiastes from './ecclesiastes';
import * as songOfSolomon from './song-of-solomon';
import * as isaiah from './isaiah';
import * as jeremiah from './jeremiah';
import * as lamentations from './lamentations';
import * as ezekiel from './ezekiel';
import * as daniel from './daniel';
import * as hosea from './hosea';
import * as joel from './joel';
import * as amos from './amos';
import * as obadiah from './obadiah';
import * as jonah from './jonah';
import * as micah from './micah';
import * as nahum from './nahum';
import * as habakkuk from './habakkuk';
import * as zephaniah from './zephaniah';
import * as haggai from './haggai';
import * as zechariah from './zechariah';
import * as malachi from './malachi';
import * as matthew from './matthew';
import * as mark from './mark';
import * as luke from './luke';
import * as john from './john';
import * as acts from './acts';
import * as romans from './romans';
import * as corinthians1 from './1-corinthians';
import * as corinthians2 from './2-corinthians';
import * as galatians from './galatians';
import * as ephesians from './ephesians';
import * as philippians from './philippians';
import * as colossians from './colossians';
import * as thessalonians1 from './1-thessalonians';
import * as thessalonians2 from './2-thessalonians';
import * as timothy1 from './1-timothy';
import * as timothy2 from './2-timothy';
import * as titus from './titus';
import * as philemon from './philemon';
import * as hebrews from './hebrews';
import * as james from './james';
import * as peter1 from './1-peter';
import * as peter2 from './2-peter';
import * as john1 from './1-john';
import * as john2 from './2-john';
import * as john3 from './3-john';
import * as jude from './jude';
import * as revelation from './revelation';

export function getBookUtils(bookSlug: string) {
  switch (bookSlug) {
    case 'exodus': return exodus;
    case 'leviticus': return leviticus;
    case 'numbers': return numbers;
    case 'deuteronomy': return deuteronomy;
    case 'joshua': return joshua;
    case 'judges': return judges;
    case 'ruth': return ruth;
    case '1-samuel': return samuel1;
    case '2-samuel': return samuel2;
    case '1-kings': return kings1;
    case '2-kings': return kings2;
    case '1-chronicles': return chronicles1;
    case '2-chronicles': return chronicles2;
    case 'ezra': return ezra;
    case 'nehemiah': return nehemiah;
    case 'esther': return esther;
    case 'job': return job;
    case 'proverbs': return proverbs;
    case 'ecclesiastes': return ecclesiastes;
    case 'song-of-solomon': return songOfSolomon;
    case 'isaiah': return isaiah;
    case 'jeremiah': return jeremiah;
    case 'lamentations': return lamentations;
    case 'ezekiel': return ezekiel;
    case 'daniel': return daniel;
    case 'hosea': return hosea;
    case 'joel': return joel;
    case 'amos': return amos;
    case 'obadiah': return obadiah;
    case 'jonah': return jonah;
    case 'micah': return micah;
    case 'nahum': return nahum;
    case 'habakkuk': return habakkuk;
    case 'zephaniah': return zephaniah;
    case 'haggai': return haggai;
    case 'zechariah': return zechariah;
    case 'malachi': return malachi;
    case 'matthew': return matthew;
    case 'mark': return mark;
    case 'luke': return luke;
    case 'john': return john;
    case 'acts': return acts;
    case 'romans': return romans;
    case '1-corinthians': return corinthians1;
    case '2-corinthians': return corinthians2;
    case 'galatians': return galatians;
    case 'ephesians': return ephesians;
    case 'philippians': return philippians;
    case 'colossians': return colossians;
    case '1-thessalonians': return thessalonians1;
    case '2-thessalonians': return thessalonians2;
    case '1-timothy': return timothy1;
    case '2-timothy': return timothy2;
    case 'titus': return titus;
    case 'philemon': return philemon;
    case 'hebrews': return hebrews;
    case 'james': return james;
    case '1-peter': return peter1;
    case '2-peter': return peter2;
    case '1-john': return john1;
    case '2-john': return john2;
    case '3-john': return john3;
    case 'jude': return jude;
    case 'revelation': return revelation;
    default: return null;
  }
}
